# Spring Boot Configuration
spring:
  # 1. Spring Boot JDBC + HikariCP 설정
  datasource:
    hikari:
      driver-class-name: org.postgresql.Driver
      jdbc-url: ${DB_JDBC_URL}
      username: ${DB_USER_NAME}
      password: ${DB_USER_PW}
      pool-name: Hikari Connection Pool  # Alias
      maximum-pool-size: 5

# Spring Boot Log4j2 Configuration
logging:
  # default Logging 프레임워크 설정 파일을 참조
  config: classpath:log4j2/log4j2-local.yml

  # Hikari Connection Pool Debug
  level:
    # Tomcat Internal Log
    org:
      apache:
        tomcat: false
        catalina: false
